#pragma once
#include <variant>
#include <string>
#include "Instruction.h"
#include <vector>
#include <unordered_map>


class Disassembler
{
private:
    const std::string filepath;
    std::vector<uint8_t> ROM;
    std::vector<Instruction> assemblyCode;


    /*
    * First we will look up in the 8 bit table. If we find that the opcode is PREFIX, we know that it is a 16 bit instruction.
    * We can then look up in the 16 bit table. Won't store 0xCB(the prefix) in 16 bit table. Only the 8 bits following the prefix.
    */

    std::unordered_map<uint8_t, Instruction> lookupTable8Bit = {
        // Row 0x0_
        {0x00, {Opcode::NOP, "", ""}},
        {0x01, {Opcode::LD, "BC", "d16"}},
        {0x02, {Opcode::LD, "(BC)", "A"}},
        {0x03, {Opcode::INC, "BC", ""}},
        {0x04, {Opcode::INC, "B", ""}},
        {0x05, {Opcode::DEC, "B", ""}},
        {0x06, {Opcode::LD, "B", "d8"}},
        {0x07, {Opcode::RLCA, "", ""}},
        {0x08, {Opcode::LD, "(a16)", "SP"}},
        {0x09, {Opcode::ADD, "HL", "BC"}},
        {0x0A, {Opcode::LD, "A", "(BC)"}},
        {0x0B, {Opcode::DEC, "BC", ""}},
        {0x0C, {Opcode::INC, "C", ""}},
        {0x0D, {Opcode::DEC, "C", ""}},
        {0x0E, {Opcode::LD, "C", "d8"}},
        {0x0F, {Opcode::RRCA, "", ""}},

        // Row 0x1_
        { 0x10, {Opcode::STOP, "", ""} },
        {0x11, {Opcode::LD, "DE", "d16"}},
        {0x12, {Opcode::LD, "(DE)", "A"}},
        {0x13, {Opcode::INC, "DE", ""}},
        {0x14, {Opcode::INC, "D", ""}},
        {0x15, {Opcode::DEC, "D", ""}},
        {0x16, {Opcode::LD, "D", "d8"}},
        {0x17, {Opcode::RLA, "", ""}},
        {0x18, {Opcode::JR, "s8", ""}},
        {0x19, {Opcode::ADD, "HL", "DE"}},
        {0x1A, {Opcode::LD, "A", "(DE)"}},
        {0x1B, {Opcode::DEC, "DE", ""}},
        {0x1C, {Opcode::INC, "E", ""}},
        {0x1D, {Opcode::DEC, "E", ""}},
        {0x1E, {Opcode::LD, "E", "d8"}},
        {0x1F, {Opcode::RRA, "", ""}},

        // Row 0x2_
        {0x20, {Opcode::JR, "NZ", "s8"}},
        {0x21, {Opcode::LD, "HL", "d16"}},
        {0x22, {Opcode::LD, "(HL+)", "A"}},
        {0x23, {Opcode::INC, "HL", ""}},
        {0x24, {Opcode::INC, "H", ""}},
        {0x25, {Opcode::DEC, "H", ""}},
        {0x26, {Opcode::LD, "H", "d8"}},
        {0x27, {Opcode::DAA, "", ""}},
        {0x28, {Opcode::JR, "Z", "s8"}},
        {0x29, {Opcode::ADD, "HL", "HL"}},
        {0x2A, {Opcode::LD, "A", "(HL+)"}},
        {0x2B, {Opcode::DEC, "HL", ""}},
        {0x2C, {Opcode::INC, "L", ""}},
        {0x2D, {Opcode::DEC, "L", ""}},
        {0x2E, {Opcode::LD, "L", "d8"}},
        {0x2F, {Opcode::CPL, "", ""}},

        // Row 0x3_
        {0x30, {Opcode::JR, "NC", "s8"}},
        {0x31, {Opcode::LD, "SP", "d16"}},
        {0x32, {Opcode::LD, "(HL-)", "A"}},
        {0x33, {Opcode::INC, "SP", ""}},
        {0x34, {Opcode::INC, "(HL)", ""}},
        {0x35, {Opcode::DEC, "(HL)", ""}},
        {0x36, {Opcode::LD, "(HL)", "d8"}},
        {0x37, {Opcode::SCF, "", ""}},
        {0x38, {Opcode::JR, "C", "s8"}},
        {0x39, {Opcode::ADD, "HL", "SP"}},
        {0x3A, {Opcode::LD, "A", "(HL-)"}},
        {0x3B, {Opcode::DEC, "SP", ""}},
        {0x3C, {Opcode::INC, "A", ""}},
        {0x3D, {Opcode::DEC, "A", ""}},
        {0x3E, {Opcode::LD, "A", "d8"}},
        {0x3F, {Opcode::CCF, "", ""}},

        // Row 0x4_
        {0x40, {Opcode::LD, "B", "B"}},
        {0x41, {Opcode::LD, "B", "C"}},
        {0x42, {Opcode::LD, "B", "D"}},
        {0x43, {Opcode::LD, "B", "E"}},
        {0x44, {Opcode::LD, "B", "H"}},
        {0x45, {Opcode::LD, "B", "L"}},
        {0x46, {Opcode::LD, "B", "(HL)"}},
        {0x47, {Opcode::LD, "B", "A"}},
        {0x48, {Opcode::LD, "C", "B"}},
        {0x49, {Opcode::LD, "C", "C"}},
        {0x4A, {Opcode::LD, "C", "D"}},
        {0x4B, {Opcode::LD, "C", "E"}},
        {0x4C, {Opcode::LD, "C", "H"}},
        {0x4D, {Opcode::LD, "C", "L"}},
        {0x4E, {Opcode::LD, "C", "(HL)"}},
        {0x4F, {Opcode::LD, "C", "A"}},

        // Row 0x5_
        {0x50, {Opcode::LD, "D", "B"}},
        {0x51, {Opcode::LD, "D", "C"}},
        {0x52, {Opcode::LD, "D", "D"}},
        {0x53, {Opcode::LD, "D", "E"}},
        {0x54, {Opcode::LD, "D", "H"}},
        {0x55, {Opcode::LD, "D", "L"}},
        {0x56, {Opcode::LD, "D", "(HL)"}},
        {0x57, {Opcode::LD, "D", "A"}},
        {0x58, {Opcode::LD, "E", "B"}},
        {0x59, {Opcode::LD, "E", "C"}},
        {0x5A, {Opcode::LD, "E", "D"}},
        {0x5B, {Opcode::LD, "E", "E"}},
        {0x5C, {Opcode::LD, "E", "H"}},
        {0x5D, {Opcode::LD, "E", "L"}},
        {0x5E, {Opcode::LD, "E", "(HL)"}},
        {0x5F, {Opcode::LD, "E", "A"}},

        // Row 0x6_
        {0x60, {Opcode::LD, "H", "B"}},
        {0x61, {Opcode::LD, "H", "C"}},
        {0x62, {Opcode::LD, "H", "D"}},
        {0x63, {Opcode::LD, "H", "E"}},
        {0x64, {Opcode::LD, "H", "H"}},
        {0x65, {Opcode::LD, "H", "L"}},
        {0x66, {Opcode::LD, "H", "(HL)"}},
        {0x67, {Opcode::LD, "H", "A"}},
        {0x68, {Opcode::LD, "L", "B"}},
        {0x69, {Opcode::LD, "L", "C"}},
        {0x6A, {Opcode::LD, "L", "D"}},
        {0x6B, {Opcode::LD, "L", "E"}},
        {0x6C, {Opcode::LD, "L", "H"}},
        {0x6D, {Opcode::LD, "L", "L"}},
        {0x6E, {Opcode::LD, "L", "(HL)"}},
        {0x6F, {Opcode::LD, "L", "A"}},

        // Row 0x7_
        {0x70, {Opcode::LD, "(HL)", "B"}},
        {0x71, {Opcode::LD, "(HL)", "C"}},
        {0x72, {Opcode::LD, "(HL)", "D"}},
        {0x73, {Opcode::LD, "(HL)", "E"}},
        {0x74, {Opcode::LD, "(HL)", "H"}},
        {0x75, {Opcode::LD, "(HL)", "L"}},
        {0x76, {Opcode::HALT, "", ""}},
        {0x77, {Opcode::LD, "(HL)", "A"}},
        {0x78, {Opcode::LD, "A", "B"}},
        {0x79, {Opcode::LD, "A", "C"}},
        {0x7A, {Opcode::LD, "A", "D"}},
        {0x7B, {Opcode::LD, "A", "E"}},
        {0x7C, {Opcode::LD, "A", "H"}},
        {0x7D, {Opcode::LD, "A", "L"}},
        {0x7E, {Opcode::LD, "A", "(HL)"}},
        {0x7F, {Opcode::LD, "A", "A"}},

        // Row 0x8_
        {0x80, {Opcode::ADD, "A", "B"}},
        {0x81, {Opcode::ADD, "A", "C"}},
        {0x82, {Opcode::ADD, "A", "D"}},
        {0x83, {Opcode::ADD, "A", "E"}},
        {0x84, {Opcode::ADD, "A", "H"}},
        {0x85, {Opcode::ADD, "A", "L"}},
        {0x86, {Opcode::ADD, "A", "(HL)"}},
        {0x87, {Opcode::ADD, "A", "A"}},
        {0x88, {Opcode::ADC, "A", "B"}},
        {0x89, {Opcode::ADC, "A", "C"}},
        {0x8A, {Opcode::ADC, "A", "D"}},
        {0x8B, {Opcode::ADC, "A", "E"}},
        {0x8C, {Opcode::ADC, "A", "H"}},
        {0x8D, {Opcode::ADC, "A", "L"}},
        {0x8E, {Opcode::ADC, "A", "(HL)"}},
        {0x8F, {Opcode::ADC, "A", "A"}},

        // Row 0x9_
        {0x90, {Opcode::SUB, "A", "B"}},
        {0x91, {Opcode::SUB, "A", "C"}},
        {0x92, {Opcode::SUB, "A", "D"}},
        {0x93, {Opcode::SUB, "A", "E"}},
        {0x94, {Opcode::SUB, "A", "H"}},
        {0x95, {Opcode::SUB, "A", "L"}},
        {0x96, {Opcode::SUB, "A", "(HL)"}},
        {0x97, {Opcode::SUB, "A", "A"}},
        {0x98, {Opcode::SBC, "A", "B"}},
        {0x99, {Opcode::SBC, "A", "C"}},
        {0x9A, {Opcode::SBC, "A", "D"}},
        {0x9B, {Opcode::SBC, "A", "E"}},
        {0x9C, {Opcode::SBC, "A", "H"}},
        {0x9D, {Opcode::SBC, "A", "L"}},
        {0x9E, {Opcode::SBC, "A", "(HL)"}},
        {0x9F, {Opcode::SBC, "A", "A"}},


        // Row 0xA_
        { 0xA0, {Opcode::AND, "A", "B"} },
        { 0xA1, {Opcode::AND, "A", "C"} },
        { 0xA2, {Opcode::AND, "A", "D"} },
        { 0xA3, {Opcode::AND, "A", "E"} },
        { 0xA4, {Opcode::AND, "A", "H"} },
        { 0xA5, {Opcode::AND, "A", "L"} },
        { 0xA6, {Opcode::AND, "A", "(HL)"} },
        { 0xA7, {Opcode::AND, "A", "A"} },
        { 0xA8, {Opcode::XOR, "A", "B"} },
        { 0xA9, {Opcode::XOR, "A", "C"} },
        { 0xAA, {Opcode::XOR, "A", "D"} },
        { 0xAB, {Opcode::XOR, "A", "E"} },
        { 0xAC, {Opcode::XOR, "A", "H"} },
        { 0xAD, {Opcode::XOR, "A", "L"} },
        { 0xAE, {Opcode::XOR, "A", "(HL)"} },
        { 0xAF, {Opcode::XOR, "A", "A"} },

        // Row 0xB_
        { 0xB0, {Opcode::OR, "A", "B"} },
        { 0xB1, {Opcode::OR, "A", "C"} },
        { 0xB2, {Opcode::OR, "A", "D"} },
        { 0xB3, {Opcode::OR, "A", "E"} },
        { 0xB4, {Opcode::OR, "A", "H"} },
        { 0xB5, {Opcode::OR, "A", "L"} },
        { 0xB6, {Opcode::OR, "A", "(HL)"} },
        { 0xB7, {Opcode::OR, "A", "A"} },
        { 0xB8, {Opcode::CP, "A", "B"} },
        { 0xB9, {Opcode::CP, "A", "C"} },
        { 0xBA, {Opcode::CP, "A", "D"} },
        { 0xBB, {Opcode::CP, "A", "E"} },
        { 0xBC, {Opcode::CP, "A", "H"} },
        { 0xBD, {Opcode::CP, "A", "L"} },
        { 0xBE, {Opcode::CP, "A", "(HL)"} },
        { 0xBF, {Opcode::CP, "A", "A"} },

        // Row 0xC_
        { 0xC0, {Opcode::RET, "NZ", ""} },
        { 0xC1, {Opcode::POP, "BC", ""} },
        { 0xC2, {Opcode::JP, "NZ", "a16"} },
        { 0xC3, {Opcode::JP, "a16", ""} },
        { 0xC4, {Opcode::CALL, "NZ", "a16"} },
        { 0xC5, {Opcode::PUSH, "BC", ""} },
        { 0xC6, {Opcode::ADD, "A", "d8"} },
        { 0xC7, {Opcode::RST, "00H", ""} },
        { 0xC8, {Opcode::RET, "Z", ""} },
        { 0xC9, {Opcode::RET, "", ""} },
        { 0xCA, {Opcode::JP, "Z", "a16"} },
        { 0xCB, {Opcode::PREFIX, "CB", ""} }, // CB-prefixed instructions
        { 0xCC, {Opcode::CALL, "Z", "a16"} },
        { 0xCD, {Opcode::CALL, "a16", ""} },
        { 0xCE, {Opcode::ADC, "A", "d8"} },
        { 0xCF, {Opcode::RST, "08H", ""} },

        // Row 0xD_
        { 0xD0, {Opcode::RET, "NC", ""} },
        { 0xD1, {Opcode::POP, "DE", ""} },
        { 0xD2, {Opcode::JP, "NC", "a16"} },
        { 0xD3, {Opcode::INVALID, "", ""} }, // Unused opcode
        { 0xD4, {Opcode::CALL, "NC", "a16"} },
        { 0xD5, {Opcode::PUSH, "DE", ""} },
        { 0xD6, {Opcode::SUB, "A", "d8"} },
        { 0xD7, {Opcode::RST, "10H", ""} },
        { 0xD8, {Opcode::RET, "C", ""} },
        { 0xD9, {Opcode::RETI, "", ""} },
        { 0xDA, {Opcode::JP, "C", "a16"} },
        { 0xDB, {Opcode::INVALID, "", ""} }, // Unused opcode
        { 0xDC, {Opcode::CALL, "C", "a16"} },
        { 0xDD, {Opcode::INVALID, "", ""} }, // Unused opcode
        { 0xDE, {Opcode::SBC, "A", "d8"} },
        { 0xDF, {Opcode::RST, "18H", ""} },

        // Row 0xE_
        { 0xE0, {Opcode::LD, "(a8)", "A"} },
        { 0xE1, {Opcode::POP, "HL", ""} },
        { 0xE2, {Opcode::LD, "(C)", "A"} },
        { 0xE3, {Opcode::INVALID, "", ""} }, // Unused opcode
        { 0xE4, {Opcode::INVALID, "", ""} }, // Unused opcode
        { 0xE5, {Opcode::PUSH, "HL", ""} },
        { 0xE6, {Opcode::AND, "A", "d8"} },
        { 0xE7, {Opcode::RST, "20H", ""} },
        { 0xE8, {Opcode::ADD, "SP", "s8"} },
        { 0xE9, {Opcode::JP, "(HL)", ""} },
        { 0xEA, {Opcode::LD, "(a16)", "A"} },
        { 0xEB, {Opcode::INVALID, "", ""} }, // Unused opcode
        { 0xEC, {Opcode::INVALID, "", ""} }, // Unused opcode
        { 0xED, {Opcode::INVALID, "", ""} }, // Unused opcode
        { 0xEE, {Opcode::XOR, "A", "d8"} },
        { 0xEF, {Opcode::RST, "28H", ""} },

        // Row 0xF_
        { 0xF0, {Opcode::LD, "A", "(a8)"} },
        { 0xF1, {Opcode::POP, "AF", ""} },
        { 0xF2, {Opcode::LD, "A", "(C)"} },
        { 0xF3, {Opcode::DI, "", ""} },
        { 0xF4, {Opcode::INVALID, "", ""} }, // Unused opcode
        { 0xF5, {Opcode::PUSH, "AF", ""} },
        { 0xF6, {Opcode::OR, "A", "d8"} },
        { 0xF7, {Opcode::RST, "30H", ""} },
        { 0xF8, {Opcode::LD, "HL", "SP+s8"} },
        { 0xF9, {Opcode::LD, "SP", "HL"} },
        { 0xFA, {Opcode::LD, "A", "(a16)"} },
        { 0xFB, {Opcode::EI, "", ""} },
        { 0xFC, {Opcode::INVALID, "", ""} }, // Unused opcode
        { 0xFD, {Opcode::INVALID, "", ""} }, // Unused opcode
        { 0xFE, {Opcode::CP, "A", "d8"} },
        { 0xFF, {Opcode::RST, "38H", ""} },

    };


    std::unordered_map<uint8_t, Instruction> lookupTable16Bit = {
        // Row 0x00_
         {0x00, {Opcode::RLC, "B", ""}},
         {0x01, {Opcode::RLC, "C", ""}},
         {0x02, {Opcode::RLC, "D", ""}},
         {0x03, {Opcode::RLC, "E", ""}},
         {0x04, {Opcode::RLC, "H", ""}},
         {0x05, {Opcode::RLC, "L", ""}},
         {0x06, {Opcode::RLC, "(HL)", ""}},
         {0x07, {Opcode::RLC, "A", ""}},
         {0x08, {Opcode::RRC, "B", ""}},
         {0x09, {Opcode::RRC, "C", ""}},
         {0x0A, {Opcode::RRC, "D", ""}},
         {0x0B, {Opcode::RRC, "E", ""}},
         {0x0C, {Opcode::RRC, "H", ""}},
         {0x0D, {Opcode::RRC, "L", ""}},
         {0x0E, {Opcode::RRC, "(HL)", ""}},
         {0x0F, {Opcode::RRC, "A", ""}},

         // Row 0x10_
         {0x10, {Opcode::RL, "B", ""}},
         {0x11, {Opcode::RL, "C", ""}},
         {0x12, {Opcode::RL, "D", ""}},
         {0x13, {Opcode::RL, "E", ""}},
         {0x14, {Opcode::RL, "H", ""}},
         {0x15, {Opcode::RL, "L", ""}},
         {0x16, {Opcode::RL, "(HL)", ""}},
         {0x17, {Opcode::RL, "A", ""}},
         {0x18, {Opcode::RR, "B", ""}},
         {0x19, {Opcode::RR, "C", ""}},
         {0x1A, {Opcode::RR, "D", ""}},
         {0x1B, {Opcode::RR, "E", ""}},
         {0x1C, {Opcode::RR, "H", ""}},
         {0x1D, {Opcode::RR, "L", ""}},
         {0x1E, {Opcode::RR, "(HL)", ""}},
         {0x1F, {Opcode::RR, "A", ""}},

         // Row 0x20_
         {0x20, {Opcode::SLA, "B", ""}},
         {0x21, {Opcode::SLA, "C", ""}},
         {0x22, {Opcode::SLA, "D", ""}},
         {0x23, {Opcode::SLA, "E", ""}},
         {0x24, {Opcode::SLA, "H", ""}},
         {0x25, {Opcode::SLA, "L", ""}},
         {0x26, {Opcode::SLA, "(HL)", ""}},
         {0x27, {Opcode::SLA, "A", ""}},
         {0x28, {Opcode::SRA, "B", ""}},
         {0x29, {Opcode::SRA, "C", ""}},
         {0x2A, {Opcode::SRA, "D", ""}},
         {0x2B, {Opcode::SRA, "E", ""}},
         {0x2C, {Opcode::SRA, "H", ""}},
         {0x2D, {Opcode::SRA, "L", ""}},
         {0x2E, {Opcode::SRA, "(HL)", ""}},
         {0x2F, {Opcode::SRA, "A", ""}},

         // Row 0x30_
         {0x30, {Opcode::SWAP, "B", ""}},
         {0x31, {Opcode::SWAP, "C", ""}},
         {0x32, {Opcode::SWAP, "D", ""}},
         {0x33, {Opcode::SWAP, "E", ""}},
         {0x34, {Opcode::SWAP, "H", ""}},
         {0x35, {Opcode::SWAP, "L", ""}},
         {0x36, {Opcode::SWAP, "(HL)", ""}},
         {0x37, {Opcode::SWAP, "A", ""}},
         {0x38, {Opcode::SRL, "B", ""}},
         {0x39, {Opcode::SRL, "C", ""}},
         {0x3A, {Opcode::SRL, "D", ""}},
         {0x3B, {Opcode::SRL, "E", ""}},
         {0x3C, {Opcode::SRL, "H", ""}},
         {0x3D, {Opcode::SRL, "L", ""}},
         {0x3E, {Opcode::SRL, "(HL)", ""}},
         {0x3F, {Opcode::SRL, "A", ""}},

         // Row 0x40_
         {0x40, {Opcode::BIT, "0", "B"}},
         {0x41, {Opcode::BIT, "0", "C"}},
         {0x42, {Opcode::BIT, "0", "D"}},
         {0x43, {Opcode::BIT, "0", "E"}},
         {0x44, {Opcode::BIT, "0", "H"}},
         {0x45, {Opcode::BIT, "0", "L"}},
         {0x46, {Opcode::BIT, "0", "(HL)"}},
         {0x47, {Opcode::BIT, "0", "A"}},
         {0x48, {Opcode::BIT, "1", "B"}},
         {0x49, {Opcode::BIT, "1", "C"}},
         {0x4A, {Opcode::BIT, "1", "D"}},
         {0x4B, {Opcode::BIT, "1", "E"}},
         {0x4C, {Opcode::BIT, "1", "H"}},
         {0x4D, {Opcode::BIT, "1", "L"}},
         {0x4E, {Opcode::BIT, "1", "(HL)"}},
         {0x4F, {Opcode::BIT, "1", "A"}},

         // Row 0x50_
         {0x50, {Opcode::BIT, "2", "B"}},
         {0x51, {Opcode::BIT, "2", "C"}},
         {0x52, {Opcode::BIT, "2", "D"}},
         {0x53, {Opcode::BIT, "2", "E"}},
         {0x54, {Opcode::BIT, "2", "H"}},
         {0x55, {Opcode::BIT, "2", "L"}},
         {0x56, {Opcode::BIT, "2", "(HL)"}},
         {0x57, {Opcode::BIT, "2", "A"}},
         {0x58, {Opcode::BIT, "3", "B"}},
         {0x59, {Opcode::BIT, "3", "C"}},
         {0x5A, {Opcode::BIT, "3", "D"}},
         {0x5B, {Opcode::BIT, "3", "E"}},
         {0x5C, {Opcode::BIT, "3", "H"}},
         {0x5D, {Opcode::BIT, "3", "L"}},
         {0x5E, {Opcode::BIT, "3", "(HL)"}},
         {0x5F, {Opcode::BIT, "3", "A"}},

         // Row 0x60_
         {0x60, {Opcode::BIT, "4", "B"}},
         {0x61, {Opcode::BIT, "4", "C"}},
         {0x62, {Opcode::BIT, "4", "D"}},
         {0x63, {Opcode::BIT, "4", "E"}},
         {0x64, {Opcode::BIT, "4", "H"}},
         {0x65, {Opcode::BIT, "4", "L"}},
         {0x66, {Opcode::BIT, "4", "(HL)"}},
         {0x67, {Opcode::BIT, "4", "A"}},
         {0x68, {Opcode::BIT, "5", "B"}},
         {0x69, {Opcode::BIT, "5", "C"}},
         {0x6A, {Opcode::BIT, "5", "D"}},
         {0x6B, {Opcode::BIT, "5", "E"}},
         {0x6C, {Opcode::BIT, "5", "H"}},
         {0x6D, {Opcode::BIT, "5", "L"}},
         {0x6E, {Opcode::BIT, "5", "(HL)"}},
         {0x6F, {Opcode::BIT, "5", "A"}},

         // Row 0x70_
         { 0x70, {Opcode::BIT, "6", "B"} },
         { 0x71, {Opcode::BIT, "6", "C"} },
         { 0x72, {Opcode::BIT, "6", "D"} },
         { 0x73, {Opcode::BIT, "6", "E"} },
         { 0x74, {Opcode::BIT, "6", "H"} },
         { 0x75, {Opcode::BIT, "6", "L"} },
         { 0x76, {Opcode::BIT, "6", "(HL)"} },
         { 0x77, {Opcode::BIT, "6", "A"} },
         { 0x78, {Opcode::BIT, "7", "B"} },
         { 0x79, {Opcode::BIT, "7", "C"} },
         { 0x7A, {Opcode::BIT, "7", "D"} },
         { 0x7B, {Opcode::BIT, "7", "E"} },
         { 0x7C, {Opcode::BIT, "7", "H"} },
         { 0x7D, {Opcode::BIT, "7", "L"} },
         { 0x7E, {Opcode::BIT, "7", "(HL)"} },
         { 0x7F, {Opcode::BIT, "7", "A"} },

         // Row 0x80_
         { 0x80, {Opcode::RES, "0", "B"} },
         { 0x81, {Opcode::RES, "0", "C"} },
         { 0x82, {Opcode::RES, "0", "D"} },
         { 0x83, {Opcode::RES, "0", "E"} },
         { 0x84, {Opcode::RES, "0", "H"} },
         { 0x85, {Opcode::RES, "0", "L"} },
         { 0x86, {Opcode::RES, "0", "(HL)"} },
         { 0x87, {Opcode::RES, "0", "A"} },
         { 0x88, {Opcode::RES, "1", "B"} },
         { 0x89, {Opcode::RES, "1", "C"} },
         { 0x8A, {Opcode::RES, "1", "D"} },
         { 0x8B, {Opcode::RES, "1", "E"} },
         { 0x8C, {Opcode::RES, "1", "H"} },
         { 0x8D, {Opcode::RES, "1", "L"} },
         { 0x8E, {Opcode::RES, "1", "(HL)"} },
         { 0x8F, {Opcode::RES, "1", "A"} },

         // Row 0x90_
         { 0x90, {Opcode::RES, "2", "B"} },
         { 0x91, {Opcode::RES, "2", "C"} },
         { 0x92, {Opcode::RES, "2", "D"} },
         { 0x93, {Opcode::RES, "2", "E"} },
         { 0x94, {Opcode::RES, "2", "H"} },
         { 0x95, {Opcode::RES, "2", "L"} },
         { 0x96, {Opcode::RES, "2", "(HL)"} },
         { 0x97, {Opcode::RES, "2", "A"} },
         { 0x98, {Opcode::RES, "3", "B"} },
         { 0x99, {Opcode::RES, "3", "C"} },
         { 0x9A, {Opcode::RES, "3", "D"} },
         { 0x9B, {Opcode::RES, "3", "E"} },
         { 0x9C, {Opcode::RES, "3", "H"} },
         { 0x9D, {Opcode::RES, "3", "L"} },
         { 0x9E, {Opcode::RES, "3", "(HL)"} },
         { 0x9F, {Opcode::RES, "3", "A"} },

         // Row 0xA0_
         { 0xA0, {Opcode::RES, "4", "B"} },
         { 0xA1, {Opcode::RES, "4", "C"} },
         { 0xA2, {Opcode::RES, "4", "D"} },
         { 0xA3, {Opcode::RES, "4", "E"} },
         { 0xA4, {Opcode::RES, "4", "H"} },
         { 0xA5, {Opcode::RES, "4", "L"} },
         { 0xA6, {Opcode::RES, "4", "(HL)"} },
         { 0xA7, {Opcode::RES, "4", "A"} },
         { 0xA8, {Opcode::RES, "5", "B"} },
         { 0xA9, {Opcode::RES, "5", "C"} },
         { 0xAA, {Opcode::RES, "5", "D"} },
         { 0xAB, {Opcode::RES, "5", "E"} },
         { 0xAC, {Opcode::RES, "5", "H"} },
         { 0xAD, {Opcode::RES, "5", "L"} },
         { 0xAE, {Opcode::RES, "5", "(HL)"} },
         { 0xAF, {Opcode::RES, "5", "A"} },

         // Row 0xB0_
         { 0xB0, {Opcode::RES, "6", "B"} },
         { 0xB1, {Opcode::RES, "6", "C"} },
         { 0xB2, {Opcode::RES, "6", "D"} },
         { 0xB3, {Opcode::RES, "6", "E"} },
         { 0xB4, {Opcode::RES, "6", "H"} },
         { 0xB5, {Opcode::RES, "6", "L"} },
         { 0xB6, {Opcode::RES, "6", "(HL)"} },
         { 0xB7, {Opcode::RES, "6", "A"} },
         { 0xB8, {Opcode::RES, "7", "B"} },
         { 0xB9, {Opcode::RES, "7", "C"} },
         { 0xBA, {Opcode::RES, "7", "D"} },
         { 0xBB, {Opcode::RES, "7", "E"} },
         { 0xBC, {Opcode::RES, "7", "H"} },
         { 0xBD, {Opcode::RES, "7", "L"} },
         { 0xBE, {Opcode::RES, "7", "(HL)"} },
         { 0xBF, {Opcode::RES, "7", "A"} },

         // Row 0xC0_
         { 0xC0, {Opcode::SET, "0", "B"} },
         { 0xC1, {Opcode::SET, "0", "C"} },
         { 0xC2, {Opcode::SET, "0", "D"} },
         { 0xC3, {Opcode::SET, "0", "E"} },
         { 0xC4, {Opcode::SET, "0", "H"} },
         { 0xC5, {Opcode::SET, "0", "L"} },
         { 0xC6, {Opcode::SET, "0", "(HL)"} },
         { 0xC7, {Opcode::SET, "0", "A"} },
         { 0xC8, {Opcode::SET, "1", "B"} },
         { 0xC9, {Opcode::SET, "1", "C"} },
         { 0xCA, {Opcode::SET, "1", "D"} },
         { 0xCB, {Opcode::SET, "1", "E"} },
         { 0xCC, {Opcode::SET, "1", "H"} },
         { 0xCD, {Opcode::SET, "1", "L"} },
         { 0xCE, {Opcode::SET, "1", "(HL)"} },
         { 0xCF, {Opcode::SET, "1", "A"} },

         // Row 0xD0_
         { 0xD0, {Opcode::SET, "2", "B"} },
         { 0xD1, {Opcode::SET, "2", "C"} },
         { 0xD2, {Opcode::SET, "2", "D"} },
         { 0xD3, {Opcode::SET, "2", "E"} },
         { 0xD4, {Opcode::SET, "2", "H"} },
         { 0xD5, {Opcode::SET, "2", "L"} },
         { 0xD6, {Opcode::SET, "2", "(HL)"} },
         { 0xD7, {Opcode::SET, "2", "A"} },
         { 0xD8, {Opcode::SET, "3", "B"} },
         { 0xD9, {Opcode::SET, "3", "C"} },
         { 0xDA, {Opcode::SET, "3", "D"} },
         { 0xDB, {Opcode::SET, "3", "E"} },
         { 0xDC, {Opcode::SET, "3", "H"} },
         { 0xDD, {Opcode::SET, "3", "L"} },
         { 0xDE, {Opcode::SET, "3", "(HL)"} },
         { 0xDF, {Opcode::SET, "3", "A"} },

         // Row 0xE0_
         { 0xE0, {Opcode::SET, "4", "B"} },
         { 0xE1, {Opcode::SET, "4", "C"} },
         { 0xE2, {Opcode::SET, "4", "D"} },
         { 0xE3, {Opcode::SET, "4", "E"} },
         { 0xE4, {Opcode::SET, "4", "H"} },
         { 0xE5, {Opcode::SET, "4", "L"} },
         { 0xE6, {Opcode::SET, "4", "(HL)"} },
         { 0xE7, {Opcode::SET, "4", "A"} },
         { 0xE8, {Opcode::SET, "5", "B"} },
         { 0xE9, {Opcode::SET, "5", "C"} },
         { 0xEA, {Opcode::SET, "5", "D"} },
         { 0xEB, {Opcode::SET, "5", "E"} },
         { 0xEC, {Opcode::SET, "5", "H"} },
         { 0xED, {Opcode::SET, "5", "L"} },
         { 0xEE, {Opcode::SET, "5", "(HL)"} },
         { 0xEF, {Opcode::SET, "5", "A"} },

         // Row 0xF0_
         { 0xF0, {Opcode::SET, "6", "B"} },
         { 0xF1, {Opcode::SET, "6", "C"} },
         { 0xF2, {Opcode::SET, "6", "D"} },
         { 0xF3, {Opcode::SET, "6", "E"} },
         { 0xF4, {Opcode::SET, "6", "H"} },
         { 0xF5, {Opcode::SET, "6", "L"} },
         { 0xF6, {Opcode::SET, "6", "(HL)"} },
         { 0xF7, {Opcode::SET, "6", "A"} },
         { 0xF8, {Opcode::SET, "7", "B"} },
         { 0xF9, {Opcode::SET, "7", "C"} },
         { 0xFA, {Opcode::SET, "7", "D"} },
         { 0xFB, {Opcode::SET, "7", "E"} },
         { 0xFC, {Opcode::SET, "7", "H"} },
         { 0xFD, {Opcode::SET, "7", "L"} },
         { 0xFE, {Opcode::SET, "7", "(HL)"} },
         { 0xFF, {Opcode::SET, "7", "A"} },


    };


public:
    Disassembler(const std::string& filepath);
    void parseFile();
    Instruction fetchInstructionAt(int i);
    
};

